aliyun:
  oss:
    access-key-id: # Your access-key
    access-key-secret: # Your access-key-secret
    bucket-domain: # Your bucket-domain
    bucket-name: # bucket-name
    end-point: http://oss-cn-shenzhen.aliyuncs.com
server:
  port: 5000
spring:
  application:
    name: my-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: # Your Redis Host
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
