server:
  port: 80
spring:
  application:
    name: crowd-zuul
  redis:
    host: # Your Redis host
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: '*'
  # 在 Zuul 向其他微服务重定向时保持原本头信息（请求头、响应头）
  sensitive-headers: '*'
  routes:
    crowd-portal:
      service-id: crowd-auth
      # 这里一定要使用两个 * 号，不然 / 路径后面的多层路径将无法访问
      path: /**
    crowd-project:
      service-id: my-crowd-project
      # 这里一定要使用两个 * 号，不然 / 路径后面的多层路径将无法访问
      path: /project/**
ribbon:
  ReadTimeout: 10000
  ConnectTimeOut: 10000