server:
  port: 4000
spring:
  application:
    name: crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
short:
  message:
    appcode: Your Code
    host: Your host
    method: GET
    path: Your path
    sign: 1
    skin: 17
ribbon:
  ReadTimeout: 10000
  ConnectTimeOut: 10000